require("configuration.theme")
require("configuration.layouts")
require("configuration.bindings")
require("configuration.screen")
require("configuration.rules")
require("configuration.notifications")
