working_directory = "/home/georgi/projects/vikings/"
live_config_reload = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 10

[mouse]
hide_when_typing = true

[window]
opacity = 0.94
dynamic_title = true

decorations = "transparent"
startup_mode = "Maximized"
decorations_theme_variant = "dark"

# [window.dimensions]
# columns = 220
# lines = 65

[window.padding]
x = 25
y = 25

[colors.primary]
background = "#15141b"
foreground = "#edecee"

[colors.cursor]
cursor = "#a277ff"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#110f18"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[colors.bright]
black = "#4d4d4d"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"


[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[font]
size = 13.0

[font.italic]
family = "Hack"
style = "SemiBold"

[font.normal]
family = "Hack"
style = "Regular"

[font.bold]
family = "Hack"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[debug]
render_timer = false
persistent_logging = false

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Control"
